export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const ADD_ORDER = "ADD_ORDER";
export const CHANGE_ORDER_STATUS = "CHANGE_ORDER_STATUS";
